version: '3.7'

services:
  sudoku-frontend:
    tty: true
    image: jonch009/sudoku-frontend:develop
    container_name: sudoku-frontend
    mem_limit: 2048m
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true